package recommendation

import (
	"example.com/sync/internal/model"
	"strings"
	"unicode"
)

// Release confidence is metadata evidence, not certification of ownership or
// human authorship. YouTube supplies no universal official-release/OAC field.
type ReleaseEvidence struct {
	Confidence string   `json:"release_confidence"`
	Evidence   []string `json:"release_evidence"`
}

func ReleaseConfidence(v model.YouTubeVideo) ReleaseEvidence {
	r := ReleaseEvidence{Confidence: "UNKNOWN", Evidence: []string{}}
	if v.LicensedContent {
		r.Confidence = "HIGH"
		r.Evidence = append(r.Evidence, "licensedContent=true")
	}
	name := strings.ToLower(strings.TrimSpace(v.ChannelTitle))
	if strings.HasSuffix(name, " - topic") {
		r.Evidence = append(r.Evidence, "topic channel-name heuristic")
		if r.Confidence != "HIGH" {
			r.Confidence = "MEDIUM"
		}
	}
	if strings.HasSuffix(name, "vevo") {
		r.Evidence = append(r.Evidence, "VEVO channel-name heuristic")
		if r.Confidence != "HIGH" {
			r.Confidence = "MEDIUM"
		}
	}
	if strings.Contains(strings.ToLower(v.Description), "provided to youtube by") {
		r.Evidence = append(r.Evidence, "distributor description heuristic")
		if r.Confidence != "HIGH" {
			r.Confidence = "MEDIUM"
		}
	}
	for _, p := range []string{"official audio", "official video", "official mv", "music video"} {
		if phrase(v.Title, p) {
			r.Evidence = append(r.Evidence, "weak title: "+p)
			if r.Confidence == "UNKNOWN" {
				r.Confidence = "LOW"
			}
			break
		}
	}
	if strings.Contains(strings.ToLower(v.Description), "auto-generated by youtube") {
		r.Evidence = append(r.Evidence, "YouTube distribution label; not generative AI evidence")
	}
	return r
}

type LanguageSignal struct {
	Value    string `json:"value"`
	Strength string `json:"strength"`
	Source   string `json:"source"`
}
type LanguageEvidence struct {
	Affinity          string         `json:"language_affinity"`
	Evidence          []string       `json:"language_evidence"`
	Confidence        string         `json:"language_confidence"`
	AudioLanguage     LanguageSignal `json:"audio_language"`
	TextLanguage      LanguageSignal `json:"text_language"`
	TitleScript       LanguageSignal `json:"title_script"`
	DescriptionScript LanguageSignal `json:"description_script"`
	RetrievalAffinity LanguageSignal `json:"retrieval_affinity"`
	GenreAffinity     LanguageSignal `json:"genre_affinity"`
	CoverageLanguage  string         `json:"vocal_coverage_language"`
	CoverageEligible  bool           `json:"vocal_coverage_eligible"`
	CoverageReason    string         `json:"vocal_coverage_reason"`
}

func languageCode(value string) string {
	value = strings.ToLower(strings.TrimSpace(strings.Split(value, "-")[0]))
	if len(value) != 2 {
		return ""
	}
	return value
}
func scriptSignal(text, source string) LanguageSignal {
	for _, r := range text {
		if unicode.In(r, unicode.Hangul) {
			return LanguageSignal{"ko", "weak", source}
		}
		if unicode.In(r, unicode.Hiragana, unicode.Katakana) {
			return LanguageSignal{"ja", "weak", source}
		}
	}
	return LanguageSignal{"unknown", "unknown", source + "; Latin script not assigned to English"}
}
func LanguageAffinity(v model.YouTubeVideo, genre, sourceLanguage string) LanguageEvidence {
	r := diagnosticAffinity(v, genre, sourceLanguage)
	r.AudioLanguage = LanguageSignal{"unknown", "unknown", "defaultAudioLanguage missing"}
	r.TextLanguage = LanguageSignal{"unknown", "unknown", "defaultLanguage missing"}
	r.TitleScript = scriptSignal(v.Title, "title script")
	r.DescriptionScript = scriptSignal(v.Description, "description script")
	r.RetrievalAffinity = LanguageSignal{"unknown", "unknown", "query direction only"}
	if sourceLanguage != "" {
		r.RetrievalAffinity = LanguageSignal{sourceLanguage, "intent", "query direction only; not audio evidence"}
	}
	r.GenreAffinity = LanguageSignal{"unknown", "unknown", "genre orientation only"}
	if KoreanGenre(genre) {
		r.GenreAffinity = LanguageSignal{"ko", "intent", "Korean-oriented genre; not audio evidence"}
	}
	if lang := languageCode(v.DefaultLanguage); lang != "" {
		r.TextLanguage = LanguageSignal{lang, "weak", "defaultLanguage: upload title/description metadata"}
	}
	if lang := languageCode(v.DefaultAudioLanguage); lang != "" {
		r.AudioLanguage = LanguageSignal{lang, "strong", "defaultAudioLanguage: reported audio metadata, not verified singing"}
	}
	r.CoverageLanguage = "unknown"
	r.CoverageReason = "no sufficient audio/vocal evidence; text/script/retrieval hints do not count"
	switch {
	case len(NonSongReasons(v)) > 0:
		r.CoverageReason = "non-song form excluded from vocal-language coverage"
	case VocalKind(v) == "instrumental":
		r.CoverageReason = "strong instrumental metadata; audio language does not establish vocal language"
	case r.AudioLanguage.Strength == "strong":
		r.CoverageLanguage = r.AudioLanguage.Value
		r.CoverageEligible = true
		r.CoverageReason = "reported audio language and no strong instrumental/non-song contradiction; plausible, not certified vocals"
	}
	return r
}
func diagnosticAffinity(v model.YouTubeVideo, genre, sourceLanguage string) LanguageEvidence {
	r := LanguageEvidence{Affinity: "unknown", Confidence: "unknown", Evidence: []string{}}
	if sourceLanguage != "" {
		r.Evidence = append(r.Evidence, "retrieval direction="+sourceLanguage+" (not song language)")
	}
	if lang := languageCode(v.DefaultAudioLanguage); lang != "" {
		r.Affinity = lang
		r.Confidence = "strong"
		r.Evidence = append(r.Evidence, "defaultAudioLanguage metadata")
		return r
	}
	if lang := languageCode(v.DefaultLanguage); lang != "" {
		r.Affinity = lang
		r.Confidence = "weak"
		r.Evidence = append(r.Evidence, "defaultLanguage upload metadata")
		return r
	}
	for _, ch := range v.Title {
		if unicode.In(ch, unicode.Hangul) {
			r.Affinity = "ko"
			r.Confidence = "weak"
			r.Evidence = append(r.Evidence, "Hangul title; affinity only")
			return r
		}
		if unicode.In(ch, unicode.Hiragana, unicode.Katakana) {
			r.Affinity = "ja"
			r.Confidence = "weak"
			r.Evidence = append(r.Evidence, "kana title; affinity only")
			return r
		}
	}
	for _, lang := range []struct {
		code    string
		phrases []string
	}{{"en", []string{"english lyrics", "language english", "english song"}}, {"ko", []string{"korean lyrics", "language korean"}}, {"ja", []string{"japanese lyrics", "language japanese"}}} {
		for _, p := range lang.phrases {
			if phrase(v.Title+" "+v.Description, p) {
				r.Affinity = lang.code
				r.Confidence = "weak"
				r.Evidence = append(r.Evidence, "explicit metadata phrase: "+p)
				return r
			}
		}
	}
	if KoreanGenre(genre) {
		r.Affinity = "ko"
		r.Confidence = "weak"
		r.Evidence = append(r.Evidence, "Korean-oriented source genre; affinity only")
	}
	// Latin script and a language-specific search alone do not identify language.
	return r
}

// Reuses existing V2 bucket thresholds without changing popularity scoring.
func PopularityBucket(views uint64) string { return popularityBucket(views) }

type MoodAudit struct {
	SearchRank                 int      `json:"search_rank"`
	SearchRankContribution     float64  `json:"search_rank_contribution"`
	MoodKeywordContribution    float64  `json:"mood_keyword_contribution"`
	GenreKeywordContribution   float64  `json:"genre_keyword_contribution"`
	PreferredGenreContribution float64  `json:"preferred_genre_contribution"`
	LanguageContribution       float64  `json:"language_contribution"`
	MoodKeywordMatches         []string `json:"mood_keyword_matches"`
	GenreKeywordMatches        []string `json:"genre_keyword_matches"`
	TitleMoodMatches           []string `json:"title_mood_matches"`
	Score                      float64  `json:"mood_score"`
	TempoCompatibility         string   `json:"tempo_compatibility"`
	EnergyCompatibility        string   `json:"energy_compatibility"`
}

func AuditMood(v model.YouTubeVideo, rank int, a model.ImageAnalysis, p model.MusicPreferences) MoodAudit {
	text := v.Title + " " + v.Description + " " + v.ChannelTitle
	genreWeight := .30
	if len(p.PreferredGenres) == 0 {
		genreWeight = .40
	}
	r := MoodAudit{SearchRank: rank, SearchRankContribution: .15 * clamp(1-float64(rank)/20), MoodKeywordContribution: .40 * matchFraction(text, a.Mood.Tags), GenreKeywordContribution: genreWeight * matchFraction(text, a.MusicProfile.Genres), PreferredGenreContribution: .10 * matchFraction(text, p.PreferredGenres), Score: moodScore(v, rank, a, p), TempoCompatibility: "not used by current formula; no audio tempo evidence", EnergyCompatibility: "not used by current formula; no audio energy evidence", MoodKeywordMatches: []string{}, GenreKeywordMatches: []string{}, TitleMoodMatches: []string{}}
	if languageMatch(v, p) {
		r.LanguageContribution = .05
	}
	for _, tag := range a.Mood.Tags {
		if phrase(text, tag) {
			r.MoodKeywordMatches = append(r.MoodKeywordMatches, tag)
		}
		if phrase(v.Title, tag) {
			r.TitleMoodMatches = append(r.TitleMoodMatches, tag)
		}
	}
	for _, g := range a.MusicProfile.Genres {
		if phrase(text, g) {
			r.GenreKeywordMatches = append(r.GenreKeywordMatches, g)
		}
	}
	return r
}
