package recommendation

import (
	"example.com/sync/internal/model"
	"testing"
)

func TestContentDiagnosticsOnly(t *testing.T) {
	for _, tc := range []struct {
		v        model.YouTubeVideo
		category string
		ai       bool
	}{
		{model.YouTubeVideo{Title: "What Happens When a Korean Guy Sings a KOREAN INDIE SONG to STRANGERS…?"}, "street_performance", false},
		{model.YouTubeVideo{Title: "Beat for sale"}, "type_beat", false},
		{model.YouTubeVideo{Title: "FREE Type Beat (prod. X)"}, "type_beat", false},
		{model.YouTubeVideo{Title: "Official Live at Seoul"}, "live_performance", false},
		{model.YouTubeVideo{Title: "Acoustic Cover"}, "cover_performance", false},
		{model.YouTubeVideo{Title: "[AI Worship] Song"}, "worship_generated", true},
		{model.YouTubeVideo{Description: "Made with Suno"}, "unknown", true},
		{model.YouTubeVideo{Description: "Generated with AI"}, "unknown", true},
		{model.YouTubeVideo{Title: "Song", ChannelTitle: "Artist - Topic", Description: "Provided to YouTube by Distributor\nAuto-generated by YouTube."}, "normal_track", false},
		{model.YouTubeVideo{Title: "Song", ChannelTitle: "Artist - Topic", Description: "Auto-generated by YouTube."}, "unknown", false},
	} {
		r := DiagnoseContent(tc.v)
		if r.Category != tc.category || r.AILabeled != tc.ai {
			t.Fatal(tc, r)
		}
	}
	v := model.YouTubeVideo{Title: "Official Live Cover", LicensedContent: true}
	before := NonSongReasons(v)
	DiagnoseContent(v)
	if len(before) != len(NonSongReasons(v)) || ReleaseConfidence(v).Confidence != "HIGH" {
		t.Fatal("diagnostic changed eligibility")
	}
}
