// Package recommendation provides deterministic metadata heuristics. These are
// signals about videos, never proof of artist identity, AI origin or mood.
package recommendation

import (
	"example.com/sync/internal/model"
	"strings"
	"unicode"
)

func normalize(s string) string {
	return strings.Join(strings.Fields(strings.Map(func(r rune) rune {
		if unicode.IsLetter(r) || unicode.IsNumber(r) {
			return unicode.ToLower(r)
		}
		return ' '
	}, s)), " ")
}
func phrase(text, value string) bool {
	value = normalize(value)
	return value != "" && strings.Contains(" "+normalize(text)+" ", " "+value+" ")
}

var aiPhrases = []string{"ai cover", "ai generated", "generated by ai", "ai song", "ai music", "artificial intelligence cover", "ai 커버", "ai 노래", "ai 음악", "인공지능 커버", "ai assisted music", "music created with ai", "song created with ai", "musical track and lyrics created by me with ai assistance", "ai composed", "suno ai"}
var transformationPhrases = []string{"slowed", "reverb", "sped up", "nightcore", "1 hour", "1hr", "loop", "compilation", "full album", "playlist", "mix", "mashup", "fanmade", "fan made", "fan upload", "karaoke", "팬메이드", "슬로우드", "스페드 업", "1시간", "노래방"}

// Description is used for explicit AI claims. Transformation checks use title:
// official descriptions often link playlists or mixes unrelated to this video.
// Word boundaries prevent "mix" from matching "remix", or "AI" matching a name.
func ExclusionReason(v model.YouTubeVideo) string {
	for _, p := range aiPhrases {
		if phrase(v.Title+" "+v.Description, p) {
			return "explicit AI content phrase"
		}
	}
	for _, p := range transformationPhrases {
		if phrase(v.Title, p) {
			return "transformed or collection content phrase"
		}
	}
	return ""
}
