package recommendation

import (
	"example.com/sync/internal/model"
	"math"
	"strings"
	"testing"
)

func neutralAnalysis() model.ImageAnalysis {
	return model.ImageAnalysis{Mood: model.MoodAnalysis{Primary: "cinematic", Secondary: []string{"dreamy", "reflective"}}, MusicProfile: model.MusicProfile{Tempo: "slow-medium", GenreCandidates: []model.GenreCandidate{{Category: "city-retro", Name: "city-pop", Score: .86}, {Category: "korean", Name: "k-indie", Score: .82}, {Category: "electronic", Name: "chillwave", Score: .77}}}, Confidence: &model.AnalysisConfidence{Genre: .84}}
}
func TestNeutralQ1AndAdaptiveRoles(t *testing.T) {
	p := model.MusicPreferences{Languages: []string{"ko", "en"}, Count: 10, VocalMode: "mixed"}
	plan, err := PlanNeutral(neutralAnalysis(), p, 50, "song")
	if err != nil || plan.Q1.Query != "city pop song -mix -playlist -compilation -backing -karaoke" || plan.Q1.Order != "relevance" || plan.Q1.Language != nil || plan.Q1.Mood != nil || plan.Q1.MaxResults != 50 {
		t.Fatal(plan, err)
	}
	for _, word := range []string{"korean", "english", "cinematic", "dreamy"} {
		if strings.Contains(plan.Q1.Query, word) {
			t.Fatal(plan)
		}
	}
	sufficient := CandidateStrength{PoolCount: 15, ReleaseTrusted: 15, Medium: 4, Established: 6, MedianViews: 100000, UniqueChannels: 5, LanguageCounts: map[string]int{"ko": 3, "en": 3}}
	for _, tc := range []struct {
		name                  string
		modify                func(*CandidateStrength)
		role, language, order string
	}{
		{"skip", func(*CandidateStrength) {}, "", "", ""},
		{"english coverage", func(s *CandidateStrength) { s.LanguageCounts["en"] = 0 }, "language_coverage", "en", "relevance"},
		{"korean coverage", func(s *CandidateStrength) { s.LanguageCounts["ko"] = 0 }, "language_coverage", "ko", "relevance"},
		{"unknown", func(s *CandidateStrength) { s.LanguageCounts = map[string]int{"unknown": 15} }, "language_coverage", "ko", "relevance"},
		{"popularity", func(s *CandidateStrength) { s.Medium = 0; s.Established = 0; s.Discovery = 15 }, "popularity_rescue", "", "viewCount"},
		{"discovery majority", func(s *CandidateStrength) { s.Discovery = 11 }, "popularity_rescue", "", "viewCount"},
		{"zero established", func(s *CandidateStrength) { s.Established = 0; s.Medium = 8 }, "popularity_rescue", "", "viewCount"},
		{"low median", func(s *CandidateStrength) { s.MedianViews = 9999 }, "popularity_rescue", "", "viewCount"},
		{"quantity", func(s *CandidateStrength) { s.PoolCount = 8 }, "popularity_rescue", "", "viewCount"},
		{"release", func(s *CandidateStrength) { s.ReleaseTrusted = 2 }, "popularity_rescue", "", "viewCount"},
		{"diversity", func(s *CandidateStrength) { s.UniqueChannels = 1 }, "popularity_rescue", "", "viewCount"},
	} {
		t.Run(tc.name, func(t *testing.T) {
			s := sufficient
			s.LanguageCounts = map[string]int{"ko": 3, "en": 3}
			tc.modify(&s)
			d, q := DecideNeutral(plan, s, p, DefaultNeutralPolicy(), 3, "song")
			if d.PopularityStrengthSufficient != PopularityStrengthSufficient(s, DefaultNeutralPolicy()) {
				t.Fatal("popularity trace inconsistent", d)
			}
			if d.SelectedRole != tc.role {
				t.Fatal(d, q)
			}
			if tc.role == "" {
				if d.Q2Executed || q != nil || len(d.Reasons) != 0 {
					t.Fatal(d)
				}
				return
			}
			if q == nil || !d.Q2Executed || q.Order != tc.order {
				t.Fatal(d, q)
			}
			if tc.language != "" && (q.Language == nil || *q.Language != tc.language) {
				t.Fatal(q)
			}
			if tc.role == "popularity_rescue" && (q.Language != nil || q.Mood != nil || q.Query != plan.Q1.Query) {
				t.Fatal(q)
			}
			if strings.Contains(q.Query, "korean korean") {
				t.Fatal("duplicate language token", q)
			}
			if tc.language == "en" && strings.Contains(q.Query, "korean") {
				t.Fatal(q)
			}
		})
	}
	s := sufficient
	s.LanguageCounts = map[string]int{}
	s.PoolCount = 1
	s.ReleaseTrusted = 0
	s.Medium = 0
	s.Established = 0
	s.UniqueChannels = 1
	d, _ := DecideNeutral(plan, s, p, DefaultNeutralPolicy(), 3, "song")
	if len(d.Reasons) != 5 || d.SelectedRole != "popularity_rescue" {
		t.Fatal(d)
	}
}
func TestReleaseSignals(t *testing.T) {
	for _, tc := range []struct {
		name string
		v    model.YouTubeVideo
		want string
	}{
		{"licensed", model.YouTubeVideo{LicensedContent: true}, "HIGH"}, {"topic", model.YouTubeVideo{ChannelTitle: "Artist - Topic"}, "MEDIUM"}, {"vevo", model.YouTubeVideo{ChannelTitle: "ArtistVEVO"}, "MEDIUM"}, {"official alone", model.YouTubeVideo{Title: "Official Audio"}, "LOW"}, {"unknown", model.YouTubeVideo{Title: "A song"}, "UNKNOWN"}, {"auto label", model.YouTubeVideo{Description: "Auto-generated by YouTube."}, "UNKNOWN"}, {"distribution", model.YouTubeVideo{Description: "Provided to YouTube by Distributor\nAuto-generated by YouTube."}, "MEDIUM"},
	} {
		t.Run(tc.name, func(t *testing.T) {
			r := ReleaseConfidence(tc.v)
			if r.Confidence != tc.want {
				t.Fatal(r)
			}
			if tc.name == "auto label" || tc.name == "distribution" {
				if ExclusionReason(tc.v) != "" {
					t.Fatal("distribution confused with AI")
				}
			}
			if (tc.want == "LOW" || tc.want == "UNKNOWN") && DefaultNeutralPolicy().AllowsRelease(r.Confidence) {
				t.Fatal("release gate relaxed")
			}
		})
	}
}
func TestLanguageEvidenceConservative(t *testing.T) {
	for _, tc := range []struct {
		v                               model.YouTubeVideo
		genre, source, want, confidence string
	}{
		{model.YouTubeVideo{Title: "Latin title"}, "city-pop", "en", "unknown", "unknown"},
		{model.YouTubeVideo{Title: "은방울"}, "city-pop", "", "ko", "weak"},
		{model.YouTubeVideo{Title: "さよなら"}, "city-pop", "", "ja", "weak"},
		{model.YouTubeVideo{DefaultAudioLanguage: "en-US"}, "city-pop", "", "en", "strong"},
		{model.YouTubeVideo{DefaultLanguage: "ko"}, "city-pop", "", "ko", "weak"},
		{model.YouTubeVideo{Description: "Language: English"}, "chillwave", "", "en", "weak"},
		{model.YouTubeVideo{Title: "Latin title"}, "k-indie", "ko", "ko", "weak"},
	} {
		r := LanguageAffinity(tc.v, tc.genre, tc.source)
		if r.Affinity != tc.want || r.Confidence != tc.confidence {
			t.Fatal(r, tc)
		}
	}
}
func TestMoodAuditMatchesExistingFormula(t *testing.T) {
	a := neutralAnalysis()
	a.Mood.Tags = []string{"cinematic", "dreamy"}
	a.MusicProfile.Genres = []string{"city-pop"}
	v := model.YouTubeVideo{Title: "cinematic dreamy city pop", DefaultAudioLanguage: "en"}
	p := model.MusicPreferences{Languages: []string{"en"}}
	r := AuditMood(v, 3, a, p)
	if math.Abs(r.Score-moodScore(v, 3, a, p)) > 1e-12 {
		t.Fatal(r)
	}
	sum := r.SearchRankContribution + r.MoodKeywordContribution + r.GenreKeywordContribution + r.PreferredGenreContribution + r.LanguageContribution
	if math.Abs(clamp(sum)-r.Score) > 1e-12 || len(r.TitleMoodMatches) != 2 {
		t.Fatal(r)
	}
}
