package recommendation

import (
	"example.com/sync/internal/model"
	"math"
	"reflect"
	"testing"
)

func fixture() (model.ImageAnalysis, model.MusicPreferences) {
	a := model.ImageAnalysis{}
	a.Mood.Tags = []string{"calm", "warm"}
	a.MusicProfile.Genres = []string{"acoustic"}
	return a, model.MusicPreferences{Languages: []string{"ko", "en"}, Count: 10}
}
func candidate(id, title string, views uint64) Candidate {
	return Candidate{Video: model.YouTubeVideo{VideoID: id, Title: title, ChannelTitle: id, ChannelID: id, ViewCount: views, DurationSeconds: 240}}
}
func TestPopularityDoesNotOverrideMood(t *testing.T) {
	a, p := fixture()
	r := Rank([]Candidate{candidate("high", "calm warm acoustic", 1000000), candidate("low", "calm warm acoustic", 1000)}, a, p)
	if r[0].Video.VideoID != "high" {
		t.Fatal(r)
	}
	r = Rank([]Candidate{candidate("dance", "loud dance", 1000000000), candidate("mood", "calm warm acoustic", 1000)}, a, p)
	if r[0].Video.VideoID != "mood" {
		t.Fatal("popularity overrode clear mood", r)
	}
}
func TestLicensedBonusAndMissingCounts(t *testing.T) {
	a, p := fixture()
	v := candidate("licensed", "calm acoustic", 0)
	v.Video.LicensedContent = true
	r := Rank([]Candidate{v, candidate("other", "calm acoustic", 0)}, a, p)
	if r[0].Video.VideoID != "licensed" || len(r) != 2 || r[0].Scores.Trust <= r[1].Scores.Trust {
		t.Fatal(r)
	}
	for _, v := range r {
		if math.IsNaN(v.Scores.Final) || v.Scores.Engagement != .5 {
			t.Fatal(v)
		}
	}
}
func TestContentFiltersAndFalsePositives(t *testing.T) {
	for _, title := range []string{"AI cover of song", "AI-generated music", "generated by AI", "AI song", "AI music", "artificial intelligence cover", "AI 커버", "AI 노래", "AI 음악", "인공지능 커버", "Musical track and lyrics created by me with AI-assistance", "Song slowed + reverb", "sped-up song", "Nightcore song", "1 hour music", "1hr song", "loop song", "compilation songs", "full album", "playlist of songs", "mix of songs", "mashup", "fanmade", "fan made", "fan upload", "karaoke"} {
		if ExclusionReason(model.YouTubeVideo{Title: title}) == "" {
			t.Errorf("not excluded: %s", title)
		}
	}
	for _, title := range []string{"Ai Higuchi - Song", "Official Remix", "Official Lyrics Video", "Chair Song", "Original song"} {
		if ExclusionReason(model.YouTubeVideo{Title: title}) != "" {
			t.Errorf("false positive: %s", title)
		}
	}
	if ExclusionReason(model.YouTubeVideo{Title: "Real official song", Description: "Listen to our playlist and remix collection"}) != "" {
		t.Fatal("description link false positive")
	}
	if ExclusionReason(model.YouTubeVideo{Title: "Song", Description: "This is an AI cover"}) == "" {
		t.Fatal("AI description missed")
	}
}
func TestDedupChannelDiversityAndDiscovery(t *testing.T) {
	a, p := fixture()
	p.Count = 5
	input := []Candidate{}
	for _, id := range []string{"a", "b", "c"} {
		c := candidate(id, "calm warm acoustic", 1000000)
		c.Video.ChannelID = "same"
		input = append(input, c)
	}
	input = append(input, input[0], candidate("discovery", "calm warm acoustic", 10), candidate("middle", "calm warm acoustic", 10000), candidate("other", "calm warm acoustic", 100000))
	r := Rank(input, a, p)
	if len(r) != 5 {
		t.Fatal(r)
	}
	same, discovery := 0, false
	ids := map[string]bool{}
	for _, c := range r {
		if ids[c.Video.VideoID] {
			t.Fatal("duplicate")
		}
		ids[c.Video.VideoID] = true
		if c.Video.ChannelID == "same" {
			same++
		}
		if c.Video.VideoID == "discovery" {
			discovery = true
		}
	}
	if same > 2 || !discovery {
		t.Fatal("diversity/discovery lost", r)
	}
	if len(Rank(input[:3], a, p)) != 3 {
		t.Fatal("scarce pool cap not relaxed")
	}
}
func TestHugeCountsLanguagesBoundsAndDeterminism(t *testing.T) {
	a, p := fixture()
	input := []Candidate{candidate("zero", "calm acoustic", 0), candidate("huge", "calm acoustic", math.MaxUint64), candidate("middle", "calm acoustic", 100000)}
	likes := uint64(12345)
	input[1].Video.LikeCount = &likes
	input[0].Video.DefaultAudioLanguage = "ko-KR"
	input[2].Video.DefaultAudioLanguage = "en-US"
	r := Rank(input, a, p)
	if !reflect.DeepEqual(r, Rank(input, a, p)) {
		t.Fatal("not deterministic")
	}
	for _, c := range r {
		for _, x := range []float64{c.Scores.Mood, c.Scores.Popularity, c.Scores.Trust, c.Scores.Engagement, c.Scores.Diversity, c.Scores.Final} {
			if math.IsNaN(x) || math.IsInf(x, 0) || x < 0 || x > 1 {
				t.Fatal(x)
			}
		}
	}
	if !languageMatch(input[0].Video, p) || !languageMatch(input[2].Video, p) {
		t.Fatal("ko/en language preference ignored")
	}
	if logNormalize(math.MaxUint64, 0, math.Log10(float64(math.MaxUint64)+1)) != 1 {
		t.Fatal("log normalization")
	}
}
