package directe2e

const Page = `<!doctype html><html lang="ko"><meta charset="utf-8"><title>Sync Local Direct E2E</title><style>body{max-width:800px;margin:36px auto;font:16px system-ui;line-height:1.6;padding:0 20px}button,a{margin:8px 12px 8px 0}pre{white-space:pre-wrap}li{margin:16px 0}</style><h1>Sync Local E2E</h1><p>저장된 추천 결과로 private 테스트 플레이리스트 1개를 만듭니다.</p><a href="/api/v1/auth/google">YouTube 계정 연결</a><button id="status">연결 상태 확인</button><button id="create" disabled>Private 테스트 플레이리스트 생성</button><p id="notice"></p><ol id="tracks"></ol><pre id="result"></pre><script>
let recommendation; let attempted=false;
const notice=document.querySelector('#notice'), result=document.querySelector('#result'), create=document.querySelector('#create');
async function load(){const r=await fetch('/api/v1/e2e/recommendation');const data=await r.json();if(!r.ok){notice.textContent='추천 checkpoint가 아직 준비되지 않았습니다.';return;}recommendation=data;notice.textContent=data.returned_count+'곡 준비됨'+(data.partial?' (partial)':'');const list=document.querySelector('#tracks');list.replaceChildren();for(const track of data.tracks){const li=document.createElement('li');const link=document.createElement('a');link.textContent=track.artist+' — '+(track.track_title||track.title);link.href=track.youtube_url;link.target='_blank';link.rel='noopener';li.append(link);list.append(li);}if(data.tracks.length===0)notice.textContent='검증된 곡이 없어 playlist를 생성할 수 없습니다.';}
async function status(){const r=await fetch('/api/v1/auth/google/status',{credentials:'same-origin'});const data=await r.json();result.textContent=JSON.stringify(data,null,2);create.disabled=attempted||!data.connected||!recommendation?.tracks.length;return data;}
document.querySelector('#status').onclick=status;
create.onclick=async()=>{if(attempted||!recommendation?.tracks.length)return;const state=await status();if(!state.connected)return;attempted=true;create.disabled=true;const payload={title:'Sync E2E Test '+new Date().toISOString(),description:'Single-photo Direct local E2E test.',privacy_status:'private',tracks:recommendation.tracks.map(t=>({video_id:t.video_id}))};try{const r=await fetch('/api/v1/playlists',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload),signal:AbortSignal.timeout(160000)});const data=await r.json();result.textContent=JSON.stringify(data,null,2);notice.textContent=r.ok?'Playlist 응답을 저장했습니다.':'Playlist 단계 실패: 추천은 다시 실행하지 않습니다.';}catch(e){notice.textContent='Write 결과가 불확실합니다. 자동 재시도하지 않습니다.';}};
load().then(status);
</script></html>`
